### PR TITLE
Fix TTT Hard AI Subgame Selection

### LINKED ISSUE #399: TTT Single-player Hard makes some mistakes
**Description**

Catch-all ticket for TTT AI fixes as I find them:

* If there are two subgames that would both win the game if that subgame was won, the AI will pick the first one instead of the one which it could win immediately.
* On the first move, the yellow box around the "selected subgame" is always drawn

### PR DESCRIPTION
**Pull request by dylwhich**
### Description

Fixes the subgame selection algorithm of the hard TTT AI to prioritize winning the game over winning a subgame when the game can be won multiple ways.

Adds a function that just does a `checkWin()` against a copy of the game board with a hypothetical move, and uses that to check every possible move in the select subgame algorithm for hard mode. This seems fast enough, I haven't noticed any issues with it on hardware.

Also fixes the yellow 'next subgame' animation square remaining visible at its last location when a new game is started. In order for it to show up, you have to finish a game then start another, and it would be there.

### Test Instructions

Tested by playing some hard games. In particular it had trouble with the situation where these subgames are already won, with the bottom-right subgame being one move away from winning (and the center-left subgame not):
```
 X |   |   
   | X | X
   |    | 
```
Previously the AI would pick the center-left subgame, even if it had no other markers in that subgame, and ignore the bottom-right subgame, which could immediately be won.

### Ticket Links
Fixes #399 

### Readiness Checklist
- [x] I have run `make format` to format the changes
- [x] I have compiled the firmware and the changes have no warnings
- [x] I have compiled the emulator and the changes have no warnings
- [x] I have run `make cppcheck` and checked that `cppcheck_result.txt` has no warnings for the changes
- [x] I have added doxygen comments to any code used by more than one Swadge mode. This includes `/*! \file` comments with Design Philosophy, Usage, and Example sections for new headers.
- [x] I have run `make docs` and checked that `doxy_warnings.txt` has no warnings for the new code

### CODE REVIEW

File: main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c [hunk 1]
```diff
@@ -316,21 +332,85 @@ static bool selectSubgame_hard(ultimateTTT_t* ttt, int* x, int* y)
     // handle a tie??? Just use the TIE player? Yeah probably)
     // - We calculate the next possible move on that board, and then take a look at the board we'd need to win to get
     // our marker there
-    // - So... I guess we should take all the possible moves in that board, and then what...
+    // - So... I guess we should take all the possiblebest overal moves in that board, and then what...
+
+    // Who are we?
```
Comment (AEFeinstein) [inline main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c:337]: Still figuring that out myself

File: main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c [hunk 2]
```diff
@@ -1102,6 +1182,77 @@ static uint16_t analyzeSubgame(const tttPlayer_t subgame[3][3], tttPlayer_t play
...
+
+    memcpy(board, subgames, sizeof(board));
+
+    const tttPlayer_t opponent = (player == TTT_P1) ? TTT_P2 : TTT_P1;
+    tttPlayer_t turn           = player;
+    move_t lastMove            = {0};
+    memcpy(&lastMove, move, sizeof(move_t));
+    int moveNum = 0;
+
+    {
```
Comment (AEFeinstein) [inline main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c:1204]: Scoped for fun? Did this have logic at some point?

**Review by AEFeinstein — APPROVED** [review]

File: main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c (hunk 1 above)
Comment (dylwhich) [reply main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c:337]: In fairness, has anyone really been far even as decided to use even go want to do look more like possiblebest overal moves in that board? and forgotten who we really are?

File: main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c (hunk 2 above)
Comment (dylwhich) [reply main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c:1204]: Oooh yeah it did, originally there was a loop here for some reason

Comment (AEFeinstein) [reply main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c:1204]: Stray braces don't bother me much if they don't bother you

Comment (dylwhich) [reply main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c:1204]: Eh I'll fix this and the crazy comment, together they bother me just enough

Comment (AEFeinstein) [reply main/modes/games/ultimateTTT/ultimateTTTcpuPlayer.c]: I saw that comment and opted not to call you out on it. I don't like getting too nitpicky on CRs.
